apiVersion: v1
kind: Service
metadata:
  name: cert-manager-metrics
  namespace: cert-manager
  labels:
    app: cert-manager
    release: cert-manager
spec:
  ports:
  - name: metrics
    port: 9402
    protocol: TCP
    targetPort: 9402
  selector:
    app: cert-manager
    release: cert-manager
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: cert-manager
      release: cert-manager
  namespaceSelector:
    matchNames:
      - cert-manager
  endpoints:
    - port: metrics
      interval: 30s
